sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  matrix:
  - INSTANCE=ubuntu-1404-docker
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-ec2
- chef gem install kitchen-docker
- chef gem install kitchen-transport-rsync
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.yml
- travis_wait 30 /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
after_script:
- "/opt/chefdk/embedded/bin/kitchen destroy ${INSTANCE}"
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: fQPFG22agZ+Fr4CWA7GijENpCw6s7r00vvhR2wFGT7pzI7ttBNgsZHyZcJrUcM+RfPXU4+OMWFaie2IoC/lGRcXQVYycWjFWeOMca2DZdgojTJJhpSr5mStwXLKiOOlEpVbXFa2+mDAIqcOMfe1IJO7FNcsPAsh9+4dwWXpzuHZ7Q6VymGQRxfL7QIQCLcnjhrtsV4LcGV3iiNOWiKX1B2+ZDuoEME3Cpx5R9FhQicseajMSN34HsU2kgHv6vQqX2dBo/4IKI+LsCaq62oxjbQIxHNdvwOuE8zfS9T47QGZ/NSgCel2JwkcMrKmhhA2f8aNt1LPBwghu/GBUQIHaBHW6SaDWFO6FCGA9uukVn48ofYvlNogFs+kAIePcAF+9gXVw7qcYvHOoNPnAQ/KY8fO/Pow4y26EMnO9Vjv2Gxhs5p2zMtHWrqg9SSNWCY9prxQDzK2NSDtYWyz7DrLszjZ9E+FYnNEzHpPvZFQ4qvg1VsxWeUHBekBzHJ0EhezvAH4pOyI3ezpD8MvkKdi0pYB71Kw6RSH9gAW3qJB8vQ+n/eXdoPMYSy0opfEQLOPD5fq2dk/TXLSXLISlsp/toq5uvNaK5La4dsiNKGszEcrMEdmENMgfkFQuyZ9DrWcKrGRjXeq9UnxcIDunh51MYbd5g8guFdM7KA4d+kAsw5c=
